CREATE DATABASE TCC_PETSHOP;
USE TCC_PETSHOP;

CREATE TABLE ENDERECO(
    CODIGO_END INT NOT NULL,
    LOGRADOURO VARCHAR(30) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO VARCHAR(30) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    PRIMARY KEY(CODIGO_END)
    );
    
CREATE TABLE CLIENTE(
    RG VARCHAR(13),
    SEXO CHAR(1) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    STATUS BOOLEAN,
    DT__NASC DATE NOT NULL,
    E_MAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    OBSERVACAO VARCHAR(50) NOT NULL,
    CODIGO_CL INT NOT NULL,  
    CODIGO_END INT NOT NULL,
    UNIQUE (CPF),
    PRIMARY KEY (CODIGO_CL),
    FOREIGN KEY (CODIGO_END) REFERENCES ENDERECO (CODIGO_END)
);

CREATE TABLE FUNCIONARIO(
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    RG VARCHAR(13),
    SEXO CHAR(1) NOT NULL,
    DT__NASC DATE NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    CODIGO_FUNC INT NOT NULL,
    CODIGO_END INT NOT NULL,
    UNIQUE (CPF),
    PRIMARY KEY (CODIGO_FUNC),
    FOREIGN KEY (CODIGO_END) REFERENCES ENDERECO (CODIGO_END)
);

CREATE TABLE PET(
    NOME VARCHAR(30) NOT NULL,
    IDADE INT,
    SEXO CHAR(1) NOT NULL,    
    PORTE VARCHAR(30) NOT NULL,
    RACA VARCHAR(30) NOT NULL,
    ESPECIE VARCHAR(30),
    OBSERVACAO VARCHAR(50),
    CODIGO_PET INT NOT NULL,
    CODIGO_CL INT NOT NULL,
    PRIMARY KEY (CODIGO_PET),
    FOREIGN KEY (CODIGO_CL) REFERENCES CLIENTE (CODIGO_CL)
    );

CREATE TABLE SERVICO (
    CATEGORIA VARCHAR(30) NOT NULL,
    CODIGO_SERV INT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    PRECO NUMERIC(4,2) NOT NULL,
    TEMPO_ATEN TIME NOT NULL,
    CODIGO_PET INT NOT NULL,
    PRIMARY KEY (CODIGO_SERV),
    FOREIGN KEY (CODIGO_PET) REFERENCES PET (CODIGO_PET)
);

CREATE TABLE ATENDIMENTO(
	CODIGO_ATEN INT NOT NULL,
    CODIGO_SERV INT NOT NULL,
    CODIGO_FUNC INT NOT NULL,
    CODIGO_PET INT NOT NULL,
    DT_ATEN DATE NOT NULL,
    PRIMARY KEY (CODIGO_ATEN),
    FOREIGN KEY (CODIGO_SERV) REFERENCES SERVICO (CODIGO_SERV),
    FOREIGN KEY (CODIGO_FUNC) REFERENCES FUNCIONARIO (CODIGO_FUNC),
    FOREIGN KEY (CODIGO_PET) REFERENCES PET (CODIGO_PET)
);
